# ./travis.yml for MSAL android

language: android

jdk:
  - oraclejdk8

android:
  components:
    # Travis has a bug that we need to workaround to use sdk 25
    # https://github.com/travis-ci/travis-ci/issues/6059
    - tools
    - tools
    - platform-tools
    - build-tools-25.0.3
    - android-25
    - extra
    - extra-android-m2repository
    - extra-google-m2repository

env:
    global:
      - ADB_INSTALL_TIMEOUT=8

    matrix:
      - ANDROID_SDKS=android-25 ANDROID_TARGET=android-25 ANDROID_ABI=default/armeabi-v7a

before_script:
  - echo no | android create avd --force -n test -t android-$ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

before_install:
  - chmod +x gradlew

script:
  - cd $PWD
  - ./gradlew clean build connectedAndroidTest -PdisablePreDex
